name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build container
        run: docker-compose up -d --build
      - name: Execute container
        run: | 
          docker exec -u 0 webstamp-app echo "Builded"
          docker network create mynetwork
          docker run --network=mynetwork -d -p 127.0.0.1:6060:6060 --name webstamp nginx:alpine
          docker run -t --network=mynetwork appropriate/curl http://webstamp
   
  tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Install dependencies 
      run: docker exec -u 0 webstamp-app composer install -q --ignore-platform-reqs --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate Keys
      run: docker exec -u 0 webstamp-app php artisan key:generate
    - name: Run Tests
      run: docker exec -u 0 webstamp-app vendor/bin/phpunit tests/