name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build container
        run: docker-compose up -d --build
      - name: Pull image
        run: docker pull appropriate/curl:latest
      - name: Access web app
        run: docker run --network container:webstamp-app appropriate/curl -s --retry 10 --retry-connrefused http://localhost:8080/
