name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build container
        run: docker-compose up -d --build
      - name: Pull image
        run: docker pull appropriate/curl:latest
      - name: Access web db
        run: docker run --network container:webstamp-db appropriate/curl -s --retry 10 --retry-connrefused http://localhost:3306/
      - name: Access web nginx
        run: docker run --network container:webstamp-nginx appropriate/curl -s --retry 10 --retry-connrefused http://localhost:80/
