name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build container
        run: docker-compose up -d --build
      - name: Execute container
        run: docker exec webstamp-app /bin/bash
