name: Code-Coverage

on: [push]

jobs:
  code-coverage:
    runs-on: ubuntu-latest

    steps:  
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: composer install -q --ignore-platform-reqs --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4.27'
        extensions: dom, curl, libxml, mbstring, zip
        tools: composer:v2
        coverage: pcov
    - name: Execute tests
      run: vendor/bin/phpunit --verbose --coverage-text