name: Linting

on: [push]

jobs:
  linting-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: composer install -q --ignore-platform-reqs --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Run PHPCS on app
      run: vendor/bin/phpcs --standard=PSR2 app
    - name: Run PHPCS on database
      run: vendor/bin/phpcs --standard=PSR2 database/migrations
