name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build container
      run: docker-compose up -d --build
    - name: Install Dependencies
      run: docker-compose exec app composer install
    - name: Key Generate
      run: docker-compose exec app php artisan key:generate
    - name: Run Tests
      run: docker-compose exec app vendor/bin/phpunit tests/EndToEnd
