name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build container
      run: docker-compose up -d --build
    - name: Run docker ps -a
      run: docker ps -a
    - name: Install dependencies 
      run: docker exec -u 0 webstamp-app composer install -q --ignore-platform-reqs --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate Keys
      run: docker exec -u 0 webstamp-app php artisan key:generate
    - name: Run docker ps
      run: docker ps -a
    - name: Run Tests
      run: docker exec -u 0 webstamp-app vendor/bin/phpunit tests/EndToEnd
