name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    runs:
      using: 'docker'
      image: 'Dockerfile'
    steps:
    - uses: shivammathur/setup-php@v2
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '7.4'
    - uses: actions/checkout@v2
    - name: Build container
      run: docker-compose up -d --build
    - name: Install Dependencies
      run: composer install -q --ignore-platform-reqs --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Run Tests
      run: docker run --rm --entrypoint=sh webstamp-app -cx 'vendor/bin/phpunit tests/EndToEnd/'`
    - name: Run Tests
      run: vendor/bin/phpunit tests