name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    container:
      image: kenngsimply/laravelapp:v1

    services:
      db-tests:
          image: mysql:5.7
          env:
              MYSQL_ROOT_PASSWORD: W3b574mp3mbr43R
              MYSQL_USER: webstampEmbraer
              MYSQL_DATABASE: stpatool
          ports:
              - 3306:3306
      redis:
          image: redis:6-alpine
          ports:
            - 6379:6379
    steps:
    - uses: shivammathur/setup-php@v2
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '7.4'
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: composer install -q --ignore-platform-reqs --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Prepare Laravel Application
      run: |
        cp .env.testing .env
        php artisan key:generate
    - name: Migrate and seed
      run: |
        php artisan migrate --seed
    - name:
      run: |
        php artisan redis:init
    - name: Run Tests
      run: vendor/bin/phpunit tests/EndToEnd/
