name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build container
      run: docker-compose up -d
    - name: Install Dependencies
      run: docker exec -u 0 webtamp-app composer install -q --ignore-platform-reqs --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Run Tests
      run: docker exec -u 0 webstamp-app vendor/bin/phpunit tests/EndToEnd
